version: '3.7'
services:
  cisco:
    build: ./server/cisco
    volumes: 
      - ./server/cisco:/usr/src/app
    ports:
      - "8080:8080"
    hostname: cisco
  canary:
    build: ./server/canary
    volumes: 
      - ./server/canary:/usr/src/app
    ports: 
        - "3000:3000"
    hostname: canary