version: '3.7'
services:
  client: 
    build: ./client
    volumes: 
      - ./client:/usr/src/app
    ports: 
      - "3000:3000"
    hostname: client
  cisco:
    build: ./server/cisco
    volumes: 
      - ./server/cisco:/usr/src/app
    ports:
      - "8080:8080"
    hostname: cisco
    depends_on: 
      - db
  canary:
    build: ./server/canary
    volumes: 
      - ./server/canary:/usr/src/app
    ports: 
        - "3030:3030"
    hostname: canary
    depends_on: 
      - db
  db: 
    image: postgres:10
    hostname: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db 